_BASE_: [
  '../datasets/voc1.yml',
  '../runtime.yml',
  '_base_/picodet_v2.yml',
  '_base_/optimizer_300e.yml',
  '_base_/picodet_640_reader.yml',
]

# pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/PPLCNet_x2_0_pretrained.pdparams
# pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/picodet_l_320_coco.pdparams
# pretrain_weights: None
weights: output\picodet_l_320_coco\best_model 
find_unused_parameters: True
use_ema: true
epoch: 4
snapshot_epoch: 1

LCNet:
  scale: 2.0
  feature_maps: [3, 4, 5]

LCPAN:
  out_channels: 160
  # out_channels: 256

PicoHeadV2:
  conv_feat:
    name: PicoFeat
    feat_in: 160
    feat_out: 160
    # feat_in: 256
    # feat_out: 256
    num_convs: 4
    num_fpn_stride: 4
    norm_type: bn
    share_cls_reg: True
    use_se: True
  feat_in_chan: 160
  # feat_in_chan: 256

LearningRate:
  base_lr: 0.003
  schedulers:
  - !CosineDecay
    max_epochs: 5
  - !LinearWarmup
    start_factor: 0.01
    steps: 406

TrainReader:
  batch_size: 10

data_format: "NHWC"
dtype: "float32"
use_amp: True